import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Separate sidebars for each AI lifecycle
  mlLifecycleSidebar: [
    {
      type: 'category',
      label: 'Machine Learning Lifecycle',
      items: [
        'machine-learning-lifecycle/overview',
        'machine-learning-lifecycle/data-collection-preparation',
        'machine-learning-lifecycle/feature-engineering',
        'machine-learning-lifecycle/model-development',
        'machine-learning-lifecycle/training-validation',
        'machine-learning-lifecycle/deployment',
        'machine-learning-lifecycle/monitoring-maintenance',
        'machine-learning-lifecycle/resources',
        'machine-learning-lifecycle/roadmaps-learning-paths',
      ],
    },
  ],

  nlpLifecycleSidebar: [
    {
      type: 'category',
      label: 'NLP Lifecycle',
      items: [
        'nlp-lifecycle/overview',
        'nlp-lifecycle/problem-definition',
        'nlp-lifecycle/data-collection',
        'nlp-lifecycle/text-exploration-analysis',
        'nlp-lifecycle/text-preprocessing-preparation',
        'nlp-lifecycle/feature-engineering',
        'nlp-lifecycle/model-training',
        'nlp-lifecycle/model-evaluation',
        'nlp-lifecycle/model-deployment',
      ],
    },
  ],

  computerVisionLifecycleSidebar: [
    {
      type: 'category',
      label: 'Computer Vision Lifecycle',
      items: [
        'computer-vision-lifecycle/overview',
      ],
    },
  ],

  generativeAILifecycleSidebar: [
    {
      type: 'category',
      label: 'Generative AI Lifecycle',
      items: [
        'generative-ai-lifecycle/overview',
      ],
    },
  ],

  mlopsLifecycleSidebar: [
    {
      type: 'category',
      label: 'MLOps Lifecycle',
      items: [
        'mlops-lifecycle/overview',
      ],
    },
  ],
};

export default sidebars;
